package com.wenance.camunda.model;

public enum TransactionTypeEnum {

    DISBURSMENT,
    DISBURSMENT_ADJUSTMENT,
    REFUND,
    DEPOSIT,
    TRANSFER,
    REPAYMENT,
    INTEREST_APPLIED,
    WITHDRAWAL_ADJUSTMENT,
    WITHDRAWAL,
    PENALTY,
    PENALTY_APPLIED,
    PENALTIES_DUE_REDUCED,
    INTEREST_DUE_REDUCED,
    FEES_DUE_REDUCED,
    TRANSFER_ADJUSTMENT
}
